FE2 UI minor improvements
specklesystems/speckle-server pull request #1905
Opened 2023-12-12 12:59 UTC by andrewwallacespeckle

## Description & motivation
Agi and I have been having weekly calls on making improvements to the FE2 UI. A lot of the changes have come from the feedback provided by SOM.

## Changes:
**Adjust Padding of Feedback Survey TopBar**
Quick fix to ensure the correct padding is applied to items in the top callout banner (checklist/invites/feedback)

**Adjust cookie expiry for hasCompletedChecklistV1**
Although the checklist dismissed cookie has an expiry of 2 years, hasCompletedChecklistV1 expires on session, meaning it keeps coming back, even when you have completed. I updated hasCompletedChecklistV1 to be 2 years. 

**Update "Create new model" dialog with labels and Capitalise letters**
Updated title. Added Labels.

**Adjust Version options dropdown**
Add Icons. Reorder based on Designs. Adjust padding. Add colour option for menu items. This has been applied to the menus for versions and models. 

**Update Toggle Component**
New look based on designs. It's now a more obvious toggle, showing both list and card options. Clicking on either toggles the selected view. 

**Move Measure mode button**
Small changes. Simply moved the Measure Mode button further down the Viewer options menu. 

**Remove disabled state from Version button**
This button showed the disabled state, but still allowed a click. This takes you to a page with no versions, but there is a CTA to add a version from here, it was decided to just remove the disabled state and allow the user to go to this page, even if they had 0 versions, so they understood better what they were seeing.

**Add Description to Create New Model and Edit Model Dialogs**
A lot of the feedback from SOM was around how they used Model names as descriptors, making it easier for them to keep track of models/versions. FE2 steps away from this for various reasons, so a compromise was bring back the "description" field. Here, users can add the human readable information on models, making keeping track of versions a lot easier. The backend already had description, but we had nowhere in the UI to set or update it. I updated the "Rename Model" dialog to become "Edit Model" and added the description field. The description field was also added to the "Create New Model" dialog. 

## Screenshots:
<img width="252" alt="image" src="https://github.com/specklesystems/speckle-server/assets/139135120/ea5e0ca8-9f1a-4874-a6e7-eb458e993e99">
<img width="305" alt="image" src="https://github.com/specklesystems/speckle-server/assets/139135120/11f45b39-1c2a-4211-9808-d5321264b289">
<img width="213" alt="image" src="https://github.com/specklesystems/speckle-server/assets/139135120/45522ace-31f9-4015-a04f-89a49c34c8e6">
<img width="644" alt="image" src="https://github.com/specklesystems/speckle-server/assets/139135120/a8fa3bc4-99d9-4df6-a37b-3351de0a1d7e">

## Checklist:
- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [x] I have added appropriate tests.
- [x] I have updated or added relevant documentation.

2023-12-14 14:51 UTC, andrewwallacespeckle commented on packages/frontend-2/components/project/page/models/NewModelStructureItem.vue
I'm not too sure what this page is? I had ts error which I fixed, but not sure where to test or if this is used?

2023-12-15 11:16 UTC, fabis94 commented on packages/frontend-2/components/project/page/models/NewModelStructureItem.vue
@andrewwallacespeckle I think this is the new model entry row that appears in the models list/structured view once you click on "+ New" under a specific list item

2023-12-15 11:18 UTC, fabis94 commented on packages/frontend-2/components/project/page/models/NewModelStructureItem.vue
@andrewwallacespeckle There's no description field here tho (and we might not even want one there), so you're kinda misleading devs by saying that the `useForm` submit handler will also give you a `description` value.

You should remove that bit and instead just make description null or something

2023-12-15 11:20 UTC, fabis94 commented on packages/frontend-2/components/project/model-page/Versions.vue
> +    name
Instead of duplicating the fields that ProjectPageHeader needs here, you should use ProjectPageHeader's `ProjectPageProjectHeader` fragment instead

2023-12-15 11:23 UTC, fabis94 commented on packages/server/modules/core/services/branch/management.ts
> +    description: isBranchCreateInput(input)
I think since both types have the description field you can just shorten all of this to:

```
description: input.description ?? null
```

2023-12-15 11:30 UTC, fabis94 requested changes
left a few comments, looks good overall

2023-12-15 12:11 UTC, fabis94 approved these changes
lgtm

2023-12-15 13:23 UTC, merged