feat(server): resource limits on app tokens
specklesystems/speckle-server pull request #1959
Opened 2024-01-11 13:46 UTC by fabis94

2024-01-11 13:46 UTC, fabis94 commented on packages/frontend-2/error.vue
> +    class: computed(() => (isDarkTheme.value ? `dark` : ``)),
Fix for theme setting not being followed on the FE2 error page

2024-01-18 12:12 UTC, gjedlicska requested changes

2024-01-18 13:42 UTC, fabis94 commented on packages/server/modules/core/tests/apitokens.spec.ts
> +        expect(resDisallowed).to.have.status(401)
@gjedlicska that's how the current auth checks return the code, I didn't change any of that. I could change it, sure, but I'm wondering whether that won't break tests or frontend status code checks

2024-01-18 13:43 UTC, fabis94 commented on packages/server/modules/core/services/streams/management.ts
> +  const { skipAccessChecks = false } = options || {}
@gjedlicska the only usage is for that admin streams delete resolver you commented on

2024-01-19 17:14 UTC, gjedlicska approved these changes

2024-01-19 17:14 UTC, merged