[SBX-153] Persist Comment Visibility
specklesystems/speckle-server pull request #2032
Opened 2024-02-09 18:58 UTC by andrewwallacespeckle

[JIRA TICKET
](https://spockle.atlassian.net/browse/WBX-153)

## Changes:
- Add new cookie using `useSynchronizedCookie` called `discussionLoadedVersionOnly`
- Defaults to true, updates via existing toggle in discussions panel
- Changed `v-if` to `v-show` to make sure this is initialised on mount

2024-02-12 14:24 UTC, didimitrie submitted a review, later dismissed

2024-02-12 16:54 UTC, fabis94 commented on packages/frontend-2/components/viewer/comments/Comments.vue
> +const discussionLoadedVersionOnly = useSynchronizedCookie<boolean>(
Would be cleaner to put all of this together with where threadFilters actually get set up. In setup.ts `setupResourceRequest()` we define the empty `threadFilters` ref.

2024-02-12 16:54 UTC, fabis94 requested changes
minor comment, looks fine otherwise

2024-02-13 10:20 UTC, fabis94 requested changes
i'm confused about how this is supposed to work - i don't see any cookie ref anywhere anymore
is it actually persisted if you reload the page?
from the PR it just looks like you're syncing 2 refs to be in sync, but there's no logic for persisting any of those values to cookies or any other storage

2024-02-13 12:00 UTC, fabis94 approved these changes

2024-02-13 13:19 UTC, merged