feat(auth): :see_no_evil: Add Azure AD auth option
specklesystems/speckle-server pull request #204
Opened 2021-04-30 06:48 UTC by peterjgrainger

Create a new strategy to enable authentication via Azure AD

You will need to create an App registration and fill in all the environment variables :)

2021-04-30 12:03 UTC, didimitrie requested changes
Just some minor changes!

2021-04-30 12:03 UTC, didimitrie commented on packages/server/modules/auth/strategies/azure-ad.js
> +      const myUser = await findOrCreateUser({ user: user, rawProfile: _raw })
This bypasses the invite-only behaviour (which is not documented anywhere properly 😅), but check the google strategy for an example correct flow. 

Currently, if the server is invite-only, the expected behaviour is that unless invited, nobody can create an account. That's why there's a bunch of extra checks that need to go in here, but the google strategy should offer a quick copy paste: https://github.com/specklesystems/speckle-server/blob/63340c78b7f02142fdbc3db2459f5b39dba58a6d/packages/server/modules/auth/strategies/google.js#L30-L59

As I'm looking over the flow in there, i think i've spotted a bug of my very own in there. I'll detail in PR next steps for this.

2021-04-30 12:07 UTC, didimitrie commented
Ok @peterjgrainger, this looks good! (and also prompted a moment of introspection 😅 ; see #205). For now, if you'll just hack those changes in I'll merge, and will investigate #205 next week / over the weekend. 

Thanks!

2021-05-03 10:30 UTC, didimitrie commented
Hi @peterjgrainger, following up re #205: it's been "neutralised".  Please rebase off main, and the correct flow should now be implemented as in the latest version of the google strategy: https://github.com/specklesystems/speckle-server/blob/934be7c5a25ee2acff36b9a66eb40d28d786ae1c/packages/server/modules/auth/strategies/google.js#L28-L82

🙇🏻‍♂️

2021-05-03 12:13 UTC, peterjgrainger commented
@didimitrie I think that is all sorted now. Let me know if I need to change anything else.

Tested and works for me :)

2021-05-04 10:22 UTC, didimitrie commented on packages/server/.env-example
> +# STRATEGY_GOOGLE=false
this looks doubled up 😬 I'll merge, and remove it afterwards

2021-05-04 10:23 UTC, merged