[WBX-281] - 2049 Hardcoded URL in Create Application Success Dialog
specklesystems/speckle-server pull request #2053
Opened 2024-02-17 20:32 UTC by andrewwallacespeckle

[JIRA TICKET
](https://spockle.atlassian.net/jira/software/c/projects/WBX/issues/WBX-281?filter=myopenissues)

## Description & motivation
User reported the hardcoded url. Updated to use NUXT_PUBLIC_BASE_URL.

## Changes:
- Use NUXT_PUBLIC_BASE_URL to build URL

## To do before merge:
- The hardcoded url was the FE1 string. I need to confirm that this was not intentional. It is as the docs suggest, so I need to make sure this also works with the FE2 url. 

## Screenshots:
<img width="647" alt="image" src="https://github.com/specklesystems/speckle-server/assets/139135120/3098b4a7-3c69-406e-bc0d-db99446acfbb">

2024-02-19 08:55 UTC, fabis94 requested changes

2024-02-19 08:55 UTC, fabis94 commented on packages/frontend-2/components/developer-settings/CreateApplicationSuccessDialog.vue
> +    return `${baseUrl}/authn/verify/${props.application.id}/{code_challenge}`
What if baseUrl has a trailing slash? Build the URL using `new URL(...).toString()`

2024-02-19 10:41 UTC, andrewwallacespeckle commented on packages/frontend-2/components/developer-settings/CreateApplicationSuccessDialog.vue
> +    const finalUrl = `${url.toString()}/{code_challenge}`
Appending {code_challenge} after using the URL constructor prevents automatic URL encoding, keeping it as the placeholder text

2024-02-19 10:42 UTC, andrewwallacespeckle commented on packages/frontend-2/components/developer-settings/CreateApplicationSuccessDialog.vue
> +    const finalUrl = `${url.toString()}/{code_challenge}`
<img width="652" alt="image" src="https://github.com/specklesystems/speckle-server/assets/139135120/b37eea57-547d-4b38-ac79-38af1e317b5e">

2024-02-20 08:46 UTC, fabis94 approved these changes

2024-02-20 11:28 UTC, merged