feat(fe2): promo banner support
specklesystems/speckle-server pull request #2242
Opened 2024-05-03 12:50 UTC by andrewwallacespeckle

## Description & motivation

## Changes:

## To-do before merge:

2024-05-03 14:11 UTC, fabis94 commented on packages/frontend-2/components/projects/Dashboard.vue
> +    imageSrc: '~~/assets/images/banners/speckleverse.svg',
clean up unused properties

2024-05-03 14:11 UTC, fabis94 commented on packages/frontend-2/components/promo-banners/Banner.vue
> +  imageSrc: string
unused

2024-05-03 14:13 UTC, fabis94 commented on packages/frontend-2/components/promo-banners/Wrapper.vue
> +  default: () => false,
You don't necessarily always have to set defaults for cookies - set them when you actually want them to have a value. In this case it's enough for the cookie to have an undefined value, and only it being created when you set it to `true`

2024-05-03 14:13 UTC, fabis94 commented on packages/frontend-2/components/promo-banners/Wrapper.vue
> +    default: () => false
unnecessary default value, just creates an unnecessary cookie

2024-05-03 14:14 UTC, fabis94 commented on packages/frontend-2/components/promo-banners/Wrapper.vue
> +  const dismissedCookie = useSynchronizedCookie<boolean>(`banner-dismissed-${id}`)
composable invoked outside of acceptable scope

2024-05-06 06:29 UTC, fabis94 requested changes
@benjaminvo @andrewwallacespeckle 
If it's really important we can launch this already, but keep in mind that there's no expiration mechanism in the banner so for self-hosters if they don't update they'll stay around even after the hackathon is already over

2024-05-06 11:46 UTC, benjaminvo commented
> @benjaminvo @andrewwallacespeckle If it's really important we can launch this already, but keep in mind that there's no expiration mechanism in the banner so for self-hosters if they don't update they'll stay around even after the hackathon is already over

That's a good point. @andrewwallacespeckle I think we should add an expiration date to these and set it to when the hackathon starts.

2024-05-07 08:46 UTC, andrewwallacespeckle commented
Good point Fabs, I've added the expiry date mechanism.

2024-05-07 09:02 UTC, fabis94 approved these changes

2024-05-07 09:06 UTC, merged