Dim/gendo
specklesystems/speckle-server pull request #2283
Opened 2024-05-23 12:32 UTC by didimitrie

Changelog: 

Backend: 
- adds feature flag for the functionality below
- adds new gendo module in server that proxies requests to the gendo api. Images (both input and genod's response) are stored as blobs (so we don't spam the db). Rate limiting on backend is not tested but it should do the trick. 

Frontend:
- makes the controls sidebar resizable - pre-requisite for the panel to actually work and allow users to enlarge their images as well as minimize panel when choosing new view
- implements new fancy gendo button + panel 
- subscriptions are live (in a rough way) so we can live display new renders as they come in

Renders are linked to each specific **version** rather than model, though they could be linked by model too if we think that's better.

TODOs in extra PR: 
- ~~helm charty things~~
- env variables
- etc. 

Renders can be downloaded as well as previewed :)

![image](https://github.com/specklesystems/speckle-server/assets/7696515/ab15d39c-4d24-43d2-a466-7e8c60e42bf2)

![image](https://github.com/specklesystems/speckle-server/assets/7696515/324bb3db-f236-4c62-8e9e-4560b3131a7f)

and in light mode: 

![image](https://github.com/specklesystems/speckle-server/assets/7696515/32fd0881-962f-4be7-b04e-c7b412a9c3b9)

2024-05-28 07:45 UTC, didimitrie commented on packages/server/modules/gendo/migrations/20240522130000_gendo.ts
> +  if (!FF_GENDOAI_MODULE_ENABLED) return
Fixing!

2024-05-28 07:45 UTC, didimitrie commented on packages/server/modules/gendo/migrations/20240522130000_gendo.ts
> +  if (!FF_GENDOAI_MODULE_ENABLED) return
Ditto, fixin'

2024-05-28 07:46 UTC, didimitrie commented on packages/server/modules/gendo/migrations/20240522130000_gendo.ts
> +const GENDO_TABLE_NAME = 'gendo_ai_renders'
I'd love to do generalise like this, but I feel we need to roll out at least another extension before we do so :)

2024-05-28 07:46 UTC, didimitrie commented on packages/server/modules/gendo/migrations/20240522130000_gendo.ts
> +    table.text('baseImage').notNullable() // TODO: hopefull these will be blob urls and not the raw deal
I've clarified what they are - there was a bit of an evolution as we went. Initially base64 images - like our avatars - then proper blobIds :)

2024-05-28 09:25 UTC, gjedlicska approved these changes

2024-05-28 09:27 UTC, gjedlicska requested changes

2024-05-28 09:27 UTC, gjedlicska commented on utils/helm/speckle-server/templates/server/deployment.yml
> +            value: {{ .Values.server.gendoKey }}
The two keys need to be secret references, they should be loaded from the `server-vars` secret

2024-05-29 09:45 UTC, gjedlicska approved these changes

2024-05-29 09:48 UTC, merged