Alessandro/web 1388 mutation create new email
specklesystems/speckle-server pull request #2561
Opened 2024-08-01 14:58 UTC by alemagio

## Description & motivation

- emails list query
- create user email mutation
- delete user email mutation
- set primary email mutation

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-08-01 19:11 UTC, alemagio commented on packages/server/modules/core/graph/resolvers/userEmails.ts
> +    userEmails: (_parent, _args, ctx) => {
need to add pagination here

2024-08-02 07:00 UTC, fabis94 requested changes

2024-08-02 07:00 UTC, fabis94 commented on packages/server/modules/core/tests/graph/userEmails.spec.ts
> +  describe('createUserEmail mutation', () => {
All of your test cases are only validating successful execution paths. I suggest using `itEach()` to run the same queries/mutations with different kinds of params, validating what happens with invalid inputs.

2024-08-02 08:22 UTC, alemagio commented on packages/server/modules/core/graph/resolvers/userEmails.ts
> +    userEmails: (_parent, _args, ctx) => {
yeah, agree, I think we can skip it for the moment

2024-08-05 10:17 UTC, fabis94 requested changes
I'm fine with the logic, just want the typedefs to be re-organized and more appropriate for how the client is gonna use them

2024-08-05 13:39 UTC, fabis94 submitted a review, later dismissed

2024-08-05 16:39 UTC, gjedlicska approved these changes

2024-08-05 16:39 UTC, merged