feat(fe2): invite + list workspace invites
specklesystems/speckle-server pull request #2629
Opened 2024-08-09 15:38 UTC by fabis94

2024-08-09 15:47 UTC, fabis94 commented on packages/frontend-2/components/project/page/automations/Header.vue
> +        v-bind="bind"
Improved `useDebouncedTextInput` return to allow for way simpler/easier configuration of the FormTextInput component

2024-08-09 15:50 UTC, fabis94 commented on packages/frontend-2/components/settings/workspaces/members/TableHeader.vue
> +        v-bind="bind"
Improved `useDebouncedTextInput` return to allow for way simpler/easier configuration of the FormTextInput component

2024-08-09 16:37 UTC, fabis94 commented on packages/ui-components/src/components/layout/Dialog.vue
> +                class="relative z-50 flex px-6 py-3 space-x-3 shrink-0 bg-foundation-page"
None of Michal's new dialogs have a border above the button footer

2024-08-09 16:38 UTC, fabis94 commented on packages/ui-components/src/components/layout/Table.vue
> +          v-if="loading || !items"
Undefined `items` now means - show loading bar (for easy feeding in of API data)

2024-08-09 16:48 UTC, fabis94 commented on packages/frontend-2/components/settings/workspaces/members/MembersTable.vue
> +<template>
Moved+Updated Mike's table

2024-08-09 16:51 UTC, fabis94 commented on packages/server/modules/workspaces/events/eventListener.ts
> +        if (workspaceRole === Roles.Workspace.Guest) return false
cc @cdriesler

2024-08-11 21:11 UTC, cdriesler approved these changes

2024-08-12 07:40 UTC, Mikehrn requested changes
Nice 😁 Just one small thingy

2024-08-12 07:41 UTC, fabis94 commented on packages/server/modules/workspaces/events/eventListener.ts
> +        if (workspaceRole === Roles.Workspace.Guest) return false
@cdriesler There's no difference, the point is to return out. The return value is irrelevant, it'll just get awaited and then forgotten about.

I'd rather not add extra looping throughout the entire array just to filter out things. If you think the `return false` is confusing, I can make it a void return

2024-08-12 08:03 UTC, Mikehrn approved these changes

2024-08-12 08:30 UTC, merged