Alessandro/web 1659 workspace limits
specklesystems/speckle-server pull request #2733
Opened 2024-08-22 13:08 UTC by alemagio

## Description & motivation

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-08-22 13:10 UTC, alemagio commented on packages/server/modules/workspaces/repositories/workspaces.ts
> +      .count(StreamCommits.col.commitId)
@gjedlicska please have a look here, I don't trust my SQL

2024-08-22 13:10 UTC, alemagio commented on packages/server/modules/workspaces/tests/integration/workspaces.graph.spec.ts
> +const createProjectWithVersions =
I created this utility simulating the flow to create versions of a model in a project, I would like to make sure the flow is correct
@gjedlicska

2024-08-23 14:17 UTC, gjedlicska requested changes

2024-08-23 14:17 UTC, gjedlicska commented on packages/server/assets/workspacesCore/typedefs/workspaces.graphql
> +  version: WorkspaceBillingVersion
lets call this `versionCount`

2024-08-23 14:17 UTC, gjedlicska commented on packages/server/assets/workspacesCore/typedefs/workspaces.graphql
> +type WorkspaceBillingVersion {
type `WorkspaceVersionCount`

2024-08-23 14:17 UTC, gjedlicska commented on packages/server/modules/workspaces/domain/constants.ts
> +export const WORKSPACE_MAX_PROJECTS_VERSIONS = 500
This could be moved to the gatekeeper module

2024-08-23 14:17 UTC, gjedlicska commented on packages/server/modules/workspaces/repositories/workspaces.ts
> +    return Number(res.count)
prob parseInt is more correct

2024-08-23 14:17 UTC, gjedlicska commented on packages/server/modules/workspaces/repositories/workspaces.ts
> +      .join(Streams.name, Streams.col.workspaceId, Workspaces.col.id)
you can just query the `Streams` table

2024-08-26 15:53 UTC, gjedlicska approved these changes

2024-08-26 15:53 UTC, merged