Fix: Align security styling with design
specklesystems/speckle-server pull request #2777
Opened 2024-08-27 21:51 UTC by Mikehrn

Aligns the security tab with the designs and fixes some minor bugs, we can probably refactor this a bit further (more logic can move to a composable), but we can address after Sep 2

<img width="1512" alt="Screenshot 2024-08-27 at 23 35 42" src="https://github.com/user-attachments/assets/390abcc3-f072-4c16-ab65-4580fb2a63ae">

2024-08-27 22:36 UTC, andrewwallacespeckle requested changes
Nice work! 1 small change then this is good to go

2024-08-27 22:36 UTC, andrewwallacespeckle commented on packages/frontend-2/components/settings/workspaces/Security.vue
> +            <p class="font-body-xs font-medium flex-1">@{{ domain.domain }}</p>
text-body-xs

2024-08-28 08:57 UTC, andrewwallacespeckle approved these changes

2024-08-28 10:58 UTC, cdriesler approved these changes
![image](https://github.com/user-attachments/assets/4c8e1e0d-6668-4582-9416-78af7c5e93ed)

2024-08-28 11:26 UTC, Mikehrn commented
> ![image](https://private-user-images.githubusercontent.com/20760128/362253004-4c8e1e0d-6668-4582-9416-78af7c5e93ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDQ1MzUsIm5iZiI6MTcyNDg0NDIzNSwicGF0aCI6Ii8yMDc2MDEyOC8zNjIyNTMwMDQtNGM4ZTFlMGQtNjY2OC00NTgyLTk0MTYtNzhhZjdjNWU5M2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMjM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZWYwNWIwOWY3N2VmOTk5ZWQwNmY4YzU4ZjEyY2YzYTRhZTgzNDQyYzAxNjE4NTEyNzUzNGM2MDhjYjVkYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxDCGNSC3YnzpRVWCQ0GGkt5E0gVWD0WW1DIPpq5SgM)

<img width="220" alt="Screenshot 2024-08-28 at 13 25 38" src="https://github.com/user-attachments/assets/2dbc83f1-9d2b-4090-a79c-35856d0ed53c">

2024-08-28 11:26 UTC, merged