Chuck/web 1614 unify workspaceproject role creation
specklesystems/speckle-server pull request #2795
Opened 2024-08-28 16:32 UTC by cdriesler

## Description & motivation

- We have made decisions around how workspace roles will interact and imply project roles (for now) (before teams)

## Changes:

- Implements logic from [The Figma](https://www.figma.com/board/IjsE2t92YHmyTtoEqmXRsX/Workspace-Roles?t=LT7uU66QwiwRT1zD-0)

2024-08-28 18:24 UTC, gjedlicska requested changes

2024-08-28 18:24 UTC, gjedlicska commented on packages/server/modules/workspaces/services/management.ts
> +  grantStreamPermissionsFactory,
we should not invite repositories into services directly, this should be a domain / operation interface type import

2024-08-28 18:24 UTC, gjedlicska commented on packages/server/modules/workspaces/services/management.ts
>        if (
should be replaced with `userEmailsCompliantWithWorkspaceDomains` from the soon to be merged #2797 PR

2024-08-28 18:24 UTC, gjedlicska commented on packages/server/modules/workspaces/services/management.ts
> +    const defaultProjectRole = Roles.Stream.Contributor
lets lower this to stream reviewer

2024-08-28 18:24 UTC, gjedlicska commented on packages/server/modules/workspaces/services/management.ts
>      const queryAllWorkspaceProjectsGenerator = queryAllWorkspaceProjectsFactory({
this must be an injected dependency we rely on

2024-08-30 00:11 UTC, cdriesler commented
Ready for final thumbs up @gjedlicska 🫡

2024-08-30 07:56 UTC, merged