fix(workspaces): mutate on join workspace
specklesystems/speckle-server pull request #2833
Opened 2024-08-30 13:55 UTC by cdriesler

## Description & motivation

- Use new utils to also mutate on join

## Changes:

## To-do before merge:

## Screenshots:

## Validation of changes:

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-08-30 13:58 UTC, fabis94 requested changes

2024-08-30 13:58 UTC, fabis94 commented on packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue
> +        modifyObjectField(
You should always use the 2nd param of `update` - `data` - to get the actual data from the response and validate that the mutation did in fact go through successfully before you make any cache updates

2024-08-30 14:03 UTC, fabis94 commented on packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue
> +            return createUpdatedValue(({ update }) => {
@cdriesler User.workspaces has variables as well, you usually want to just evict all filtered (e.g. search specified) cache values cause there's no way to accurately tell if the new workspace fits that filter or not, and then make the cache update to the list only in non-filtered values

2024-08-30 14:08 UTC, fabis94 commented on packages/frontend-2/components/workspace/invite/DiscoverableWorkspaceBanner.vue
> +            return createUpdatedValue(({ update }) => {
Evict means - wherever that evicted value was referenced, e.g. in some kind of query living in a UI component, the query will understand that its now missing a part of its data and refetch it

2024-08-30 14:35 UTC, cdriesler commented
Ok, updated, but now it's pretty similar to the mutation when creating a workspace. Acceptable for now?

2024-09-05 09:05 UTC, fabis94 requested changes
i think u need to merge main, there's conflicts and it shows my changes here

2024-09-05 19:10 UTC, fabis94 approved these changes

2024-09-05 22:25 UTC, merged