feat(workspaces): move project to workspace
specklesystems/speckle-server pull request #2992
Opened 2024-09-13 11:10 UTC by cdriesler

## Description & motivation

- People have projects. Now they have workspaces. And they demand we allow them to move these projects into these workspaces.

## Changes:

- Adds `workspaceMutations.projects.moveToWorkspace`
- Adds `moveProjectToWorkspace` service function that:
  - Moves the project
  - Grants workspace roles in the target workspace to project members (if they don't already have them)
  - Uses default workspace project role, if relevant

2024-09-13 15:58 UTC, cdriesler commented
We're not rushing to get this in for Sat anymore, going to spend a little more time on better tests.

2024-09-15 23:57 UTC, cdriesler commented
ok done 😎

2024-09-17 10:12 UTC, gjedlicska requested changes

2024-09-17 20:19 UTC, gjedlicska approved these changes

2024-09-18 08:38 UTC, merged