chore(server): graceful shutdown
specklesystems/speckle-server pull request #3125
Opened 2024-09-25 14:49 UTC by iainsproat

## Description & motivation

When a deployment rolls out (causing a shutdown of an existing server), we see error messages from the Apollo server.

<img width="1865" alt="Screenshot 2024-09-25 at 15 49 05" src="https://github.com/user-attachments/assets/0bc502e6-180d-408f-a6a0-04cfdb851c49">

New connections were being made while the server was being shut down.

Apollo server was automatically shutting down when a `SIGTERM` or `SIGINT` signal was received; this created a race condition where it may close prior to the http server being drained of connections.

## Changes:

- apollo server should not automatically close on receiving SIGTERM/SIGINT
- the apollo server should be shutdown after the server is drained of connections, this can be sequenced by the terminus package.
- the readiness endpoint should be managed by terminus, which ensures they respond unready if the server is being shutdown.
- the shutdown timeout (grace period) can be configured via environment variable

## To-do before merge:

## Screenshots:

## Validation of changes:

<img width="875" alt="Screenshot 2024-09-26 at 19 13 08" src="https://github.com/user-attachments/assets/9e113818-fe73-4a7c-80f9-9be51dc74e62">
<img width="853" alt="Screenshot 2024-09-26 at 19 13 13" src="https://github.com/user-attachments/assets/bbb98b74-811c-4ecd-be3e-b49f87a3c786">

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

## References

2024-09-27 08:57 UTC, gjedlicska commented
this doesn't feel right to have as a module.

There is only application (express and apollo server) logic in here and no business logic.
I would put the code somewhere next to the `app.ts` file

2024-09-27 08:58 UTC, gjedlicska requested changes
this logic should not be a module, its application logic

2024-11-12 08:17 UTC, fabis94 approved these changes

2024-11-12 09:23 UTC, fabis94 commented on packages/server/modules/stats/tests/stats.spec.ts
> +    const {
// shorter
```ts
const ctx = await beforeEachContext()
server = ctx.server

;({ sendRequest } = await initializeTestServer(ctx)
```

2024-11-19 10:08 UTC, gjedlicska approved these changes

2024-11-19 10:08 UTC, merged