refactor(fe2): Send user to dashboard after tour - skip checklist
specklesystems/speckle-server pull request #3404
Opened 2024-10-28 11:30 UTC by andrewwallacespeckle

Now: After completing the "model tour" onboarding we send the user to their first sample project and show the 4-step guide.

Change to: Send the user to the Dashboard instead after completing the model tour. It's a better experience and we don't want this outdated 4-step guide.

2024-10-28 20:44 UTC, benjaminvo commented
@andrewwallacespeckle

1. Are you skipping the entire onboarding? When I visit `localhost:8081/onboarding?force=true` I'm just sent straight to the new project's page. I'd like to keep the guided journey through a 3D model but when you reach the end go to the Dashboard instead of the viewer.

2. As mentioned above, let's just send the user to the Dashboard instead of their new project.

2024-10-29 09:47 UTC, Mikehrn commented
I just tested this locally, and for me it works as described, I get the 3D tour (either with a new account or using the force flag) and then get send to my dashboard when completed. Only the last step feels a bit jumpy because it shows the model viewer page for 1-2 secs and then jumps to the dashboard


https://github.com/user-attachments/assets/88b7a014-44ce-4c04-8e81-9545ba3fd874

2024-10-29 11:37 UTC, andrewwallacespeckle commented
@benjaminvo I got my local onboarding working again if you want to get yours working again. 

In `/packages/server/.env`, there is a variable called `ONBOARDING_STREAM_CACHE_BUST_NUMBER`. Increasing this to 2 and restarting server and fe2 fixed my issue. 

<img width="752" alt="image" src="https://github.com/user-attachments/assets/e5f69c35-bcca-4a14-8e2c-e87d7af43602">

2024-10-30 12:33 UTC, benjaminvo commented
@andrewwallacespeckle I like it! Only thought is if we should add a hover tooltip to the Finish button? "First add another model" or something. I'm worried they don't why it's disabled and close the window.

2024-10-31 12:43 UTC, Mikehrn requested changes

2024-10-31 12:43 UTC, Mikehrn commented on packages/frontend-2/components/tour/Comment.vue
> +  hasAddedOverlay: boolean
Should this be a more generic `disableNext`? Because `hasAddedOverlay` is only relevant voor 1 specific TourComment

2024-10-31 12:43 UTC, Mikehrn commented on packages/frontend-2/components/tour/Onboarding.vue
>      <TourSlideshow v-if="step === 1" @next="step++" />
I think the step number maybe can be removed? I think one boolean should be enough? `showSlideshow` or something after `TourSegmentation` emitted `next`

2024-11-01 11:20 UTC, Mikehrn approved these changes

2024-11-01 11:20 UTC, merged