Adam/ifc dotnet
specklesystems/speckle-server pull request #3525
Opened 2024-11-20 12:48 UTC by adamhathcock

2024-11-21 13:05 UTC, adamhathcock commented on packages/fileimport-service/Dockerfile
> +ENTRYPOINT [ "./tini", "--", "node", "--no-experimental-fetch", "packages/fileimport-service/src/daemon.js"]
the dir tini was put in was never added to the path, not sure how it worked.

the working directory I set for tini means I had to change the path for the daemon

2024-11-26 12:09 UTC, gjedlicska requested changes

2024-11-26 12:09 UTC, gjedlicska commented on packages/fileimport-service/Dockerfile
> +    && npm install -g yarn@1.22.22 \
this is not ok, we're not using yarn 1

we're using corepack enabled yarn in the workspace root

2024-11-26 13:59 UTC, adamhathcock commented
@iainsproat I think I fixed everything about docker....need confirmation of the corepack change

2024-11-27 09:04 UTC, adamhathcock commented
Two of the example files are failing on the step parser.  I think it's because of whitespace/separator intolerance.

2024-11-28 15:16 UTC, adamhathcock commented
Need @gjedlicska to approve and merge

2024-11-29 05:33 UTC, gjedlicska approved these changes

2024-11-29 05:34 UTC, merged